### PR TITLE
Stopover Addition and Removal

### PR DESCRIPTION
**Pull request by ar5had**
#### Changes made by PR

* Removed all the warnings given by react
* Changed unnecessary xhr state variable to instance variable
* Embeded `route` state variable into a unified `stopovers` state variable
* Made dynamic addition of stopovers
* Stopover can be removed now. https://github.com/Greennav/GreenNav/issues/21
* Added battery level indiactor. It looks like material-ui slider doesnt have tooltip so I tried adding a custom tooltip as in `polymer_reference` branch, but position of tooltip wasnt vendor proof.

### CODE REVIEW

**Comment by ar5had** [comment]
scr111

**Comment by tom3012** [comment]
Hi @arshdkhn1,

thank you for your interest in GreenNav! I would like to suggest two things at the design level:

1. It would be better to have the delete button right beside the specific stopover and
2. in my opinion the stopovers should be named "to", so "from" --> "to" --> "to" --> ...

Best regards

**Comment by ar5had** [comment]
Will try to implement them by tommorow!

**Comment by ar5had** [comment]
@tom3012 Added an update. 
scr111

**Comment by arshdkhn1** [comment]
Hi @tom3012 

As you can see new stopover is added between the old stopovers. What are your thoughts on adding new stopover after the old stopovers?

Regards

**Comment by arshdkhn1** [comment]
screenshot 2017-03-07 20 24 04
If the previous ui doesnt look good, checkout the above layout for `Remove Stopover` button.

**Comment by ar5had** [comment]
scr111

**Comment by fabianbormann** [comment]
Looks really nice !

**Comment by ar5had** [comment]
@fabianbormann Thanks, I have some questions about the gsoc project which I would like to ask.

**Pull request merged**
